### ISSUE TITLE
configure branch protection, requiring review, using probot/settings

### ISSUE THREAD

**Issue by travi** [form8ion/rfcs#3]
seems like RFCs are one situation where requiring a review is pretty appropriate

**Comment by trevtrich** [comment]
yeah these are kinda awkward. the conversation is really the important artifact. so what actually gets "stored" & approved would almost be what turns into the ADR?

**Comment by travi** [comment]
yeah, agreed. i think thats the biggest confusing piece to considering both that we'll have to figure out. i do think that merging the agreed upon md file is the best way to consider it "accepted", but how often that then becomes an ADR will be an interesting thing to sort out
